import datetime

YAHOO_DATA_SOURCE = 'YahooFinance'

ASSET_CLASSES = ['VTI', 'VEA', 'VWO', 'JNK', 'IEF', 'TIP', 'LQD', 'VNQ', 'GCC']
SECTORS = ['XLC', 'XLY', 'XLP', 'XLE', 'XLF', 'XLV', 'XLI', 'XLB', 'XLRE','XLK', 'XLU']

INDUSTRIAL_PRODCUTION = 'INDPRO'
NONFARM_PAYROLLS = 'PAYEMS'
TEN_YEAR_TREASURY_YIELD_MINUS_FF = 'T10YFF'
NBER_RECESSION = 'USRECD'
KKT_BUSINESS_CYCLE_INDICATOR_SERIES = [INDUSTRIAL_PRODCUTION, NONFARM_PAYROLLS, TEN_YEAR_TREASURY_YIELD_MINUS_FF, NBER_RECESSION]
ECON_VARIABLES = [INDUSTRIAL_PRODCUTION, NONFARM_PAYROLLS,TEN_YEAR_TREASURY_YIELD_MINUS_FF,'S&P']


SHILLER_URL ='http://www.econ.yale.edu/~shiller/data/ie_data.xls'
SHILLER_SHEET_NAME = 'Data'
SHILLER_SKIP_ROW = 5

WINDOW_SIZE=252
TURBULENCE_QUANTILE=0.90

START_DATE = datetime.date(2000,1,1)
END_DATE = datetime.date(2023,11,30)